# This is a basic workflow to help you get started with Actions

name: CI Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:[push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Commit
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        # Set always-auth in npmrc
        always-auth: false
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 12.x
        # Set this option if you want the action to check for the latest available version that satisfies the version spec
        check-latest: true
        # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
        registry-url: false
        # Optional scope for authenticating against scoped registries
        scope: false

    - name: Setup Yarn
      run: npm install -g yarn && cd $GITHUB_WORKSPACE

    - name: Install Dependencies
      run: yarn install

    - name: Build and Test
      run: cd $GITHUB_WORKSPACE && yarn run build:all
